import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProviders from '@/hook/query/useReactQuery';

const AppleSDGOdicNeo = localFont({
  src: [
    {
      path: '../../public/font/AppleSDGothicNeo-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={AppleSDGOdicNeo.className}>
      <body>
        <div id="__next">
          <ReactQueryProviders>{children}</ReactQueryProviders>
        </div>
      </body>
    </html>
  );
}
